import { Footer } from '@/footer/widget'
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryProvider } from '@/shared/query-provider'
import { HeaderWrapper } from '@/header/wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex min-h-screen flex-col bg-pink-50 font-bold'}>
        <QueryProvider>
          {/* 
          // @ts-ignore */}
          <HeaderWrapper />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  )
}
